import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('../extension/background.js',import.meta.url),'utf8');
let listener,toolbar,nativeError='Specified native messaging host not found.',opened=[],calls=0;
const runtime={id:'self',getURL:p=>'chrome-extension://self/'+p,onMessage:{addListener:fn=>listener=fn},onStartup:{addListener(){}},onInstalled:{addListener(){}},sendNativeMessage:async()=>{calls++;if(nativeError)throw Error(nativeError);return {ok:true,accountId:'a',folders:[]};}};
vm.runInNewContext(code,{URL,setTimeout,chrome:{runtime,action:{onClicked:{addListener:fn=>toolbar=fn}},storage:{local:{get:async()=>({}),set:async()=>{}}},tabs:{create:async o=>opened.push(o.url),query:async()=>[]},alarms:{onAlarm:{addListener(){}}}}});
const send=message=>new Promise(resolve=>listener(message,{id:'self',url:'https://substack.com/saved'},resolve));
assert.equal((await send({action:'snapshot'})).code,'COMPANION_MISSING');
assert.equal((await send({action:'snapshot',refresh:true})).code,'COMPANION_MISSING');
nativeError='Native host has exited.';
assert.equal((await send({action:'snapshot',refresh:true})).code,'CONNECTION_FAILED');
nativeError='Access to the specified native messaging host is forbidden.';
assert.equal((await send({action:'snapshot',refresh:true})).code,'CONNECTION_FAILED');
nativeError=null;
assert.equal((await send({action:'snapshot',refresh:true})).ok,true);
const before=calls;await send({action:'snapshot'});assert.equal(calls,before);
await send({action:'snapshot',refresh:true});assert.equal(calls,before+1);
assert.equal((await send({action:'setup'})).ok,true);assert.equal(opened.pop(),'https://github.com/ankitiscracked/sublists#install');
toolbar();assert.equal(opened.pop(),'https://substack.com/saved#lists');
const manifest=JSON.parse(readFileSync(new URL('../extension/manifest.json',import.meta.url)));
assert.equal(manifest.action.default_popup,undefined);
console.log('PASS: missing vs disconnected/forbidden host, repeated retry, recovery, cache bypass, setup URL, toolbar Lists URL, no popup.');
